default[:openvswitch][:conf_dir] = '/etc/openvswitch'
default[:openvswitch][:pid_dir] = '/var/run/openvswitch'
default[:openvswitch][:init_file] = '/etc/sysconfig/openvswitch'
default[:openvswitch][:rpm_url] = 'http://sde-xcat-pre.pok.ibm.com/repos/rpms/openvswitch/openvswitch-1.10.0-4.ibm.el6.x86_64.rpm'
default[:openvswitch][:eth_name] = 'eth2'
